# Generated by Django 2.1.4 on 2019-02-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='referer',
            field=models.CharField(default='', max_length=255),
        ),
    ]
