# Generated by Django 2.1.4 on 2019-02-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190215_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='referer',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
