# Generated by Django 2.1.4 on 2019-02-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190215_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='referer',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
