# Generated by Django 2.1.4 on 2019-02-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190215_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='previous_balance',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=255),
        ),
    ]
