# Generated by Django 2.2.4 on 2019-11-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='xpub',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
