# Generated by Django 2.2.4 on 2019-11-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_wallet_xpub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='amount',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
    ]
