# Generated by Django 2.2.4 on 2019-11-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_auto_20191129_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='login_timer_count',
            field=models.IntegerField(default=0),
        ),
    ]
