# Generated by Django 2.2.4 on 2019-11-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_investor_login_timer_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='login_timer_count',
        ),
        migrations.AddField(
            model_name='investor',
            name='login_timer_on',
            field=models.BooleanField(default=False),
        ),
    ]
