# Generated by Django 2.2.4 on 2019-11-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_auto_20191129_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='login_timer',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='login_timer_on',
        ),
        migrations.AddField(
            model_name='investor',
            name='otp_sent',
            field=models.BooleanField(default=True),
        ),
    ]
