# Generated by Django 2.2.4 on 2019-11-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_auto_20191129_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='secret_answer1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='investor',
            name='secret_answer2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='investor',
            name='secret_question1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='investor',
            name='secret_question2',
            field=models.CharField(default='', max_length=255),
        ),
    ]
