# Generated by Django 2.2.4 on 2019-11-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_auto_20191129_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='login_code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
