# Generated by Django 2.2.4 on 2019-11-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_investor_login_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='otp_sent',
        ),
        migrations.AddField(
            model_name='investor',
            name='timer',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
