# Generated by Django 2.2.4 on 2019-11-30 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_auto_20191130_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='secret_answer1',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='secret_answer2',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='secret_question1',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='secret_question2',
        ),
        migrations.AddField(
            model_name='investor',
            name='pass_phrase',
            field=models.CharField(default='', max_length=255),
        ),
    ]
