# Generated by Django 2.2.4 on 2019-11-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_auto_20191201_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='timer_no',
            field=models.IntegerField(default=0),
        ),
    ]
