# Generated by Django 2.2.4 on 2019-12-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0014_investor_timer_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='login_code',
        ),
        migrations.AddField(
            model_name='investor',
            name='timer_on',
            field=models.BooleanField(default=False),
        ),
    ]
