# Generated by Django 2.2.4 on 2019-12-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0015_auto_20191201_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='callback_id',
            field=models.CharField(default='', max_length=150),
        ),
    ]
