# Generated by Django 2.2.4 on 2019-12-08 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0016_investor_callback_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='callback_id',
        ),
    ]
