# Generated by Django 2.2.4 on 2019-12-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0017_remove_investor_callback_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='referral_url',
            field=models.CharField(default='', max_length=150),
        ),
    ]
