# Generated by Django 2.2.4 on 2019-12-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0018_investor_referral_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='login_retries',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='pass_phrase',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='timer_no',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='timer_on',
        ),
        migrations.AddField(
            model_name='investor',
            name='pass_number',
            field=models.CharField(default='', max_length=4),
        ),
    ]
